config/routes.rb
Rails.application.routes.draw do

  resources :cells
  
  resources :generators do
    resources :attrs
  end

  get 'searches/search'
   get 'searches/search_models'
 get 'secondclassifications' => 'secondclassifications#index'
 get 'sample_rows/sample_rows_all' 
  
  resources :gradings
  resources :tprimarytumors

get 'mdistantmetastasis/new'
  resources :mdistantmetastasis

get "log_out" => "sessions#destroy", :as => "log_out"
get "log_in" => "sessions#new", :as => "log_in"
get "sign_up" => "users#new", :as => "sign_up"
get "searches/log_out" => "sessions#destroy", :as => "searches/log_out"

resources :users
resources :sessions
resources :clinics_lungs
resources :micrornas

root :to => 'sessions#new'

 resources :patients
  resources :firstclassifications
  resources :secondclassifications

  resources :firstclassifications do
  resources :secondclassifications   
    end
 resources :secondclassifications   
 
  resources :patients do
    resources :therapies 

    resources :pathologies
    
    end

  
  resources :tprimarytumors
  resources :gradings  
  resources :nregionallymphnodes
  

  resources :sample_sheets do 
    resources :sample_rows
  end
     resources :rna_forms 
       resources :cell_types
       resources :docs 
     resources :file_types

  resources :cell_types
 resources :rins
  resources :bioanalyzers

  

  resources :file_types
  resources :rnas

 resources :microrna_patients do 
    resources :stickurins
    resources :pathologicalurins

  end

end

app/models/rin.rb
class Rin
  include Mongoid::Document
    include Sunspot::Mongoid2
  field :measure, type: Float
  field :date, type: Date
  
  embedded_in :rna_form, :inverse_of => :rins
  
  searchable do
  text :date
     
end

end

app/controllers/rins_controller.rb
class RinsController < ApplicationController
  before_action :set_rin, only: [:show, :edit, :update, :destroy]

  # GET /rins
  # GET /rins.json
  def index
    @rins = Rin.all
  end

  # GET /rins/1
  # GET /rins/1.json
  def show
  end

  # GET /rins/new
  def new
    @rin = Rin.new
  end

  # GET /rins/1/edit
  def edit
  end

  # POST /rins
  # POST /rins.json
  def create
    @rin = Rin.new(rin_params)

    respond_to do |format|
      if @rin.save
        format.html { redirect_to @rin, notice: 'Rin was successfully created.' }
        format.json { render :show, status: :created, location: @rin }
      else
        format.html { render :new }
        format.json { render json: @rin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rins/1
  # PATCH/PUT /rins/1.json
  def update
    respond_to do |format|
      if @rin.update(rin_params)
        format.html { redirect_to @rin, notice: 'Rin was successfully updated.' }
        format.json { render :show, status: :ok, location: @rin }
      else
        format.html { render :edit }
        format.json { render json: @rin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rins/1
  # DELETE /rins/1.json
  def destroy
    @rin.destroy
    respond_to do |format|
      format.html { redirect_to rins_url, notice: 'Rin was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rin
      @rin = Rin.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rin_params
      params.require(:rin).permit(:measure, :date)
    end
end

app/views/rins/_form.html.erb
<%= form_for(@rin) do |f| %>
  <% if @rin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rin.errors.count, "error") %> prohibited this rin from being saved:</h2>

      <ul>
      <% @rin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :measure %><br>
    <%= f.text_field :measure %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.text_field :date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rins/edit.html.erb
<h1>Editing rin</h1>

<%= render 'form' %>

<%= link_to 'Show', @rin %> |
<%= link_to 'Back', rins_path %>

app/views/rins/index.html.erb
<h1>Listing rins</h1>

<table>
  <thead>
    <tr>
      <th>Measure</th>
      <th>Date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rins.each do |rin| %>
      <tr>
        <td><%= rin.measure %></td>
        <td><%= rin.date %></td>
        <td><%= link_to 'Show', rin %></td>
        <td><%= link_to 'Edit', edit_rin_path(rin) %></td>
        <td><%= link_to 'Destroy', rin, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Rin', new_rin_path %>

app/views/rins/new.html.erb
<h1>New rin</h1>

<%= render 'form' %>

<%= link_to 'Back', rins_path %>

app/views/rins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Measure:</strong>
  <%= @rin.measure %>
</p>

<p>
  <strong>Date:</strong>
  <%= @rin.date %>
</p>

<%= link_to 'Edit', edit_rin_path(@rin) %> |
<%= link_to 'Back', rins_path %>