config/routes.rb
Rails.application.routes.draw do

  resources :cells
  
  resources :generators do
    resources :attrs
  end

  get 'searches/search'
   get 'searches/search_models'
 get 'secondclassifications' => 'secondclassifications#index'
 get 'sample_rows/sample_rows_all' 
  
  resources :gradings
  resources :tprimarytumors

get 'mdistantmetastasis/new'
  resources :mdistantmetastasis

get "log_out" => "sessions#destroy", :as => "log_out"
get "log_in" => "sessions#new", :as => "log_in"
get "sign_up" => "users#new", :as => "sign_up"
get "searches/log_out" => "sessions#destroy", :as => "searches/log_out"

resources :users
resources :sessions
resources :clinics_lungs
resources :micrornas

root :to => 'sessions#new'

 resources :patients
  resources :firstclassifications
  resources :secondclassifications

  resources :firstclassifications do
  resources :secondclassifications   
    end
 resources :secondclassifications   
 
  resources :patients do
    resources :therapies 

    resources :pathologies
    
    end

  
  resources :tprimarytumors
  resources :gradings  
  resources :nregionallymphnodes
  

  resources :sample_sheets do 
    resources :sample_rows
  end
     resources :rna_forms 
       resources :cell_types
       resources :docs 
     resources :file_types

  resources :cell_types
 resources :rins
  resources :bioanalyzers

  

  resources :file_types
  resources :rnas

 resources :microrna_patients do 
    resources :stickurins
    resources :pathologicalurins

  end

end

app/models/grading.rb
class Grading
  include Mongoid::Document
   include Sunspot::Mongoid2
  
  field :name, type: String
  has_many :patients
  
  searchable do
    text :name     
end


end

app/controllers/gradings_controller.rb
class GradingsController < ApplicationController
  before_action :set_grading, only: [:show, :edit, :update, :destroy]

  # GET /gradings
  # GET /gradings.json
  def index
    @gradings = Grading.all
  end

  # GET /gradings/1
  # GET /gradings/1.json
  def show
  end

  # GET /gradings/new
  def new
    @grading = Grading.new
  end

  # GET /gradings/1/edit
  def edit
  end

  # POST /gradings
  # POST /gradings.json
  def create
    @grading = Grading.new(grading_params)

    respond_to do |format|
      if @grading.save
        format.html { redirect_to @grading, notice: 'Grading was successfully created.' }
        format.json { render :show, status: :created, location: @grading }
      else
        format.html { render :new }
        format.json { render json: @grading.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gradings/1
  # PATCH/PUT /gradings/1.json
  def update
    respond_to do |format|
      if @grading.update(grading_params)
        format.html { redirect_to @grading, notice: 'Grading was successfully updated.' }
        format.json { render :show, status: :ok, location: @grading }
      else
        format.html { render :edit }
        format.json { render json: @grading.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gradings/1
  # DELETE /gradings/1.json
  def destroy
    @grading.destroy
    respond_to do |format|
      format.html { redirect_to gradings_url, notice: 'Grading was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_grading
      @grading = Grading.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def grading_params
      params.require(:grading).permit(:id, :name)
    end
end

app/helpers/gradings_helper.rb
module GradingsHelper
end

app/views/gradings/_form.html.erb
<%= form_for(@grading) do |f| %>
  <% if @grading.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@grading.errors.count, "error") %> prohibited this grading from being saved:</h2>

      <ul>
      <% @grading.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :tumor_histopathological_grade %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit "send"%>
  </div>
<% end %>

app/views/gradings/edit.html.erb
<%= render 'form' %>


<%= link_to 'Destroy', @grading, method: :delete, data: { confirm: 'Are you sure?' } %>  |
<%= link_to 'View all values', gradings_path %> |
<%= link_to 'New grade value', new_grading_path %> |
<%= link_to 'New patient', new_patient_path %>

app/views/gradings/index.html.erb
<head>
<link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.1.1/css/bootstrap.css">
    <!-- Optional theme -->
     <link href="vendor/assets/stylesheets/bootstrap-tokenfield.css" rel="stylesheet">
    <link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.1.1/css/bootstrap-theme.min.css">
    <script src="https://code.jquery.com/jquery-2.1.0.min.js"></script>
    <!-- Latest compiled and minified JavaScript -->
    <script src="http://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.1.1/js/bootstrap.min.js"></script>
    <script src="http://cdnjs.cloudflare.com/ajax/libs/typeahead.js/0.10.1/typeahead.bundle.min.js"></script>
  <script src="vendor/assets/javascripts/bootstrap-tokenfield.js"></script>
  <script src="//cdnjs.cloudflare.com/ajax/libs/bootstrap-tokenfield/0.12.0/bootstrap-tokenfield.js" ></script> 
  <script src="vendor/assets/javascripts/bootstrap-tokenfield.js"></script>
  <script src="//cdnjs.cloudflare.com/ajax/libs/bootstrap-tokenfield/0.12.0/bootstrap-tokenfield.js" ></script> 
       <script type="text/javascript" src="http://cdnjs.cloudflare.com/ajax/libs/jquery.tablesorter/2.9.1/jquery.tablesorter.min.js"></script>
   <script type="text/javascript" src="http://mottie.github.io/tablesorter/js/jquery.tablesorter.widgets.js"></script>


  </head> 
 <div class="col-md-8">
<%= link_to 'New grade value', new_grading_path %>
</div>
 
<br>
<br>
<div class="col-md-2"></div>
<table id="myTable" class="table table-striped"><head>
  <thead>
    <tr>
      <th>tumor histopathological grade</th>
     
    </tr>
  </thead>

  <tbody>
    <% @gradings.each do |grading| %>
      <tr>
        <td><%= grading.name %></td>
        <td><%= link_to 'Show', grading %></td>
        <td><%= link_to 'Edit', edit_grading_path(grading) %></td>
        <td><%= link_to 'Destroy', grading, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/gradings/new.html.erb
<h1>New tumor histopathological grade</h1>

<%= render 'form' %>

<%= link_to 'View all grades', gradings_path %>

app/views/gradings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>tumor histopathological grade:</strong>
  <%= @grading.name %>
</p>

<%= link_to 'Edit', edit_grading_path(@grading) %> |
<%= link_to 'Destroy', @grading, method: :delete, data: { confirm: 'Are you sure?' } %>  |
<%= link_to 'View all grades', gradings_path %> |
<%= link_to 'New grade value', new_grading_path %> |
<%= link_to 'New patient', new_patient_path %>