config/routes.rb
Rails.application.routes.draw do

  resources :cells
  
  resources :generators do
    resources :attrs
  end

  get 'searches/search'
   get 'searches/search_models'
 get 'secondclassifications' => 'secondclassifications#index'
 get 'sample_rows/sample_rows_all' 
  
  resources :gradings
  resources :tprimarytumors

get 'mdistantmetastasis/new'
  resources :mdistantmetastasis

get "log_out" => "sessions#destroy", :as => "log_out"
get "log_in" => "sessions#new", :as => "log_in"
get "sign_up" => "users#new", :as => "sign_up"
get "searches/log_out" => "sessions#destroy", :as => "searches/log_out"

resources :users
resources :sessions
resources :clinics_lungs
resources :micrornas

root :to => 'sessions#new'

 resources :patients
  resources :firstclassifications
  resources :secondclassifications

  resources :firstclassifications do
  resources :secondclassifications   
    end
 resources :secondclassifications   
 
  resources :patients do
    resources :therapies 

    resources :pathologies
    
    end

  
  resources :tprimarytumors
  resources :gradings  
  resources :nregionallymphnodes
  

  resources :sample_sheets do 
    resources :sample_rows
  end
     resources :rna_forms 
       resources :cell_types
       resources :docs 
     resources :file_types

  resources :cell_types
 resources :rins
  resources :bioanalyzers

  

  resources :file_types
  resources :rnas

 resources :microrna_patients do 
    resources :stickurins
    resources :pathologicalurins

  end

end

app/models/secondclassification.rb
class Secondclassification
  include Mongoid::Document
  include Sunspot::Mongoid2
  
  field :name, type: String
   field :firstclassification_id, type: Integer
   
 has_many :patients, autosave: true
 belongs_to :firstclassification
 
 searchable do
    text :name
end

end

app/controllers/secondclassifications_controller.rb
class SecondclassificationsController < ApplicationController
  def create
    @firstclassification = Firstclassification.find(params[:firstclassification_id])
    @secondclassification = @firstclassification.secondclassifications.create!(secondclassification_params)
    redirect_to @firstclassification, :notice => ""  
  end
  
  def new
    
  end
  
  def edit
    
  end
  
  def index
    
    @search = Secondclassification.search do
    fulltext params[:query_classification]
   end

  @classifications = @search.results
  respond_to do |format|
    format.html
    format.json {    render :json => @classifications.map(&:attributes) }
  end
end 

  
 

  private
def secondclassification_params
      params.require(:secondclassification).permit(:id, :name, :_destroy)
    end
end

app/helpers/secondclassifications_helper.rb
module SecondclassificationsHelper
end

app/views/secondclassifications/_form.html.erb
 <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.collection_select :firstclassification_id, @firstclassifications, :id, :name %>
  </div>

app/views/secondclassifications/index.html.erb
<head>
<link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.1.1/css/bootstrap.css">
    <!-- Optional theme -->
     <link href="vendor/assets/stylesheets/bootstrap-tokenfield.css" rel="stylesheet">
    <link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.1.1/css/bootstrap-theme.min.css">
    <script src="https://code.jquery.com/jquery-2.1.0.min.js"></script>
    <!-- Latest compiled and minified JavaScript -->
    <script src="http://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.1.1/js/bootstrap.min.js"></script>
    <script src="http://cdnjs.cloudflare.com/ajax/libs/typeahead.js/0.10.1/typeahead.bundle.min.js"></script>
  <script src="vendor/assets/javascripts/bootstrap-tokenfield.js"></script>
  <script src="//cdnjs.cloudflare.com/ajax/libs/bootstrap-tokenfield/0.12.0/bootstrap-tokenfield.js" ></script> 
  <script src="vendor/assets/javascripts/bootstrap-tokenfield.js"></script>
  <script src="//cdnjs.cloudflare.com/ajax/libs/bootstrap-tokenfield/0.12.0/bootstrap-tokenfield.js" ></script> 
       <script type="text/javascript" src="http://cdnjs.cloudflare.com/ajax/libs/jquery.tablesorter/2.9.1/jquery.tablesorter.min.js"></script>
   <script type="text/javascript" src="http://mottie.github.io/tablesorter/js/jquery.tablesorter.widgets.js"></script>


  </head> 
    <body>
	
	 <div id="scrollable-dropdown-menu" class="col-md-5">
 <%= form_tag secondclassifications_path, :method => :get do %><%= text_field_tag :query_classification, 
 	params[:query_classification], autocomplete: "off", placeholder: "leave blank to see all second and second classifications" %>
</div>

<%= submit_tag "   Search   ", :name => nil %>
<% end %>
<br>
<br>
 <div class="col-md-2">
<%= link_to 'Add second classification', new_secondclassification_path %>
</div>
 
<br>
<br>
<div class="col-md-2"></div>
<table id="myTable" class="table table-striped"><head>
  <thead>
    <tr>
      <th>second classifications</th>
         </tr>
  </thead>

  <tbody>

    <% @classifications.each do |classification| %>
      <tr>
      	
        <td><%= classification.name %></td>
        
		

		
       
        	<td><%= link_to 'Show', classification %></td> 
       
  		
		      	<% end %>
  	</tr>
       
       
      	
 
      
      </table>
 
      </body>

app/views/secondclassifications/show.html.erb
<p>
  <b>Name:</b>
  <%= @secondclassification.name %>
</p>

<p>
  <b>Second classifications:</b><br/>
  <% for second in @secondclassification.secondclassifications do  %>
  <%= second.name %><br/>
  <%end%>
</p>

<%= link_to 'Edit', edit_secondclassification_path(@secondclassification) %> |
<%= link_to 'Destroy', @secondclassification, method: :delete, data: { confirm: 'Are you sure?' } %>  |
<%= link_to 'New classification', new_secondclassification_path %> |
<%= link_to 'View all classifications', secondclassifications_path %> |
<%= link_to 'new patient', new_patient_path %>