config/routes.rb
Rails.application.routes.draw do

  resources :cells
  
  resources :generators do
    resources :attrs
  end

  get 'searches/search'
   get 'searches/search_models'
 get 'secondclassifications' => 'secondclassifications#index'
 get 'sample_rows/sample_rows_all' 
  
  resources :gradings
  resources :tprimarytumors

get 'mdistantmetastasis/new'
  resources :mdistantmetastasis

get "log_out" => "sessions#destroy", :as => "log_out"
get "log_in" => "sessions#new", :as => "log_in"
get "sign_up" => "users#new", :as => "sign_up"
get "searches/log_out" => "sessions#destroy", :as => "searches/log_out"

resources :users
resources :sessions
resources :clinics_lungs
resources :micrornas

root :to => 'sessions#new'

 resources :patients
  resources :firstclassifications
  resources :secondclassifications

  resources :firstclassifications do
  resources :secondclassifications   
    end
 resources :secondclassifications   
 
  resources :patients do
    resources :therapies 

    resources :pathologies
    
    end

  
  resources :tprimarytumors
  resources :gradings  
  resources :nregionallymphnodes
  

  resources :sample_sheets do 
    resources :sample_rows
  end
     resources :rna_forms 
       resources :cell_types
       resources :docs 
     resources :file_types

  resources :cell_types
 resources :rins
  resources :bioanalyzers

  

  resources :file_types
  resources :rnas

 resources :microrna_patients do 
    resources :stickurins
    resources :pathologicalurins

  end

end

app/models/cell.rb
class Cell
 include Mongoid::Document
include Sunspot::Mongoid2
  
  field :label, type: String
  has_many :rna_forms, autosave: true
 
 searchable do
    text :label
end

end

app/controllers/cells_controller.rb
class CellsController < ApplicationController


  before_action :set_cell, only: [:show, :edit, :update, :destroy]
   

  # GET /cells
  # GET /cells.json
  def index
     @search = Cell.search do
    fulltext params[:query_cells]
   
  end
  @cells = @search.results
  respond_to do |format|
    format.html
    format.json {    render :json => @cells.map(&:attributes) }
  end
  
  
  
  end
  
 


  # GET /cells/1
  # GET /cells/1.json
  def show
  end

  # GET /cells/new
  def new
    @cell = Cell.new
  end

  # GET /cells/1/edit
  def edit
  end

  # POST /cells
  # POST /cells.json
  def create
    @cell = Cell.new(cell_params)

    respond_to do |format|
      if @cell.save
        format.html { redirect_to @cell, notice: 'Cell type was successfully created.' }
        format.json { render :show, status: :created, location: @cell }
      else
        format.html { render :new }
        format.json { render json: @cell.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cells/1
  # PATCH/PUT /cells/1.json
  def update
    respond_to do |format|
      if @cell.update(cell_params)
        format.html { redirect_to @cell, notice: 'Cell type was successfully updated.' }
        format.json { render :show, status: :ok, location: @cell }
      else
        format.html { render :edit }
        format.json { render json: @cell.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cells/1
  # DELETE /cells/1.json
  def destroy
    @cell.destroy
    respond_to do |format|
      format.html { redirect_to cells_url, notice: 'Cell type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cell
   @cell = Cell.find(params[:id]) 
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cell_params
      params.require(:cell).permit(:label, :id, :label_tokens)
    end
end

app/helpers/cells_helper.rb
module CellsHelper
end

app/views/cells/_form.html.erb
<%= form_for(@cell) do |f| %>
  <% if @cell.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cell.errors.count, "error") %> prohibited this cell from being saved:</h2>

      <ul>
      <% @cell.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :label %><br>
    <%= f.text_field :label %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cells/edit.html.erb
<h1>Editing cell type</h1>

<%= render 'form' %>

<%= link_to 'Destroy', @cell, method: :delete, data: { confirm: 'Are you sure?' } %>|
<%= link_to "New cell type", new_cell_path %> | 
 <%= link_to "View all cell types", cells_path %> 

app/views/cells/index.html.erb
<head>
<link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.1.1/css/bootstrap.css">
    <!-- Optional theme -->
     <link href="vendor/assets/stylesheets/bootstrap-tokenfield.css" rel="stylesheet">
    <link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.1.1/css/bootstrap-theme.min.css">
    <script src="https://code.jquery.com/jquery-2.1.0.min.js"></script>
    <!-- Latest compiled and minified JavaScript -->
    <script src="http://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.1.1/js/bootstrap.min.js"></script>
    <script src="http://cdnjs.cloudflare.com/ajax/libs/typeahead.js/0.10.1/typeahead.bundle.min.js"></script>
  <script src="vendor/assets/javascripts/bootstrap-tokenfield.js"></script>
  <script src="//cdnjs.cloudflare.com/ajax/libs/bootstrap-tokenfield/0.12.0/bootstrap-tokenfield.js" ></script> 
  <script src="vendor/assets/javascripts/bootstrap-tokenfield.js"></script>
  <script src="//cdnjs.cloudflare.com/ajax/libs/bootstrap-tokenfield/0.12.0/bootstrap-tokenfield.js" ></script> 
       <script type="text/javascript" src="http://cdnjs.cloudflare.com/ajax/libs/jquery.tablesorter/2.9.1/jquery.tablesorter.min.js"></script>
   <script type="text/javascript" src="http://mottie.github.io/tablesorter/js/jquery.tablesorter.widgets.js"></script>


  </head> 
    <body>
    	
	
<div id="scrollable-dropdown-menu" class="col-md-8">
	
  
 <%= form_tag cells_path, :method => :get do %><%= text_field_tag :query_cells, 
 	params[:query_cells], autocomplete: "off", placeholder: "search" %>
 	</div>
<%= submit_tag "   Search   ", :name => nil %>
<% end %>
<% 2.times do %> 
<br></br>
  <% end %> 
	 <div class="col-md-8"></div>
<div><%= link_to 'New Cell type', new_cell_path %></div>




  
<div class="col-md-8">
<table id="myTable" class="table table-striped"><head>


  <thead>
    <tr>
      <th>Label</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cells.each do |cell| %>
      <tr>
        <td><%= cell.label %></td>
        <td><%= link_to 'Show', cell %></td>
        <td><%= link_to 'Edit', edit_cell_path(cell) %></td>
        <td><%= link_to 'Destroy', cell, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

</body>
</div>

app/views/cells/new.html.erb
<h1>New cell type</h1>

<%= render 'form' %>

<%= link_to 'View all cell types', cells_path %>

app/views/cells/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Label:</strong>
  <%= @cell.label %>
</p>

<%= link_to "Edit", edit_cell_path(@cell) %> | 
<%= link_to 'Destroy', @cell, method: :delete, data: { confirm: 'Are you sure?' } %>|
<%= link_to "New cell type", new_cell_path %> | 
 <%= link_to "View all cell types", cells_path %> 